apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProvider
metadata:
  name: nankim-vault-key
spec:
  provider: azure
  parameters:
    rolename: "admin"
    useVMManagedIdentity: "true"
    keyvaultName: "nankim-vault-key"
    userAssignedIdentityID: "ee751826-effa-4c06-830a-0cb882c18e8b"
    objects:  |
      array:
        - |
          objectName: nk-secret-key
          objectType: secret             
    tenantId: "tid"        
