apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: LoadBalancer
  externalIPs:
  - 192.168.0.10
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: nk-node-server-start