apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nk-express-ingress
  namespace: staging
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    name: nk-express-ingress
spec: 
  defaultBackend:
    resource:
      apiGroup: k8s.example.com
      kind: StorageBucket
      name: staging
  rules:
  - host: nk-express-host.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nk-express
            port:
             number: 3000
           
