# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: staging
# ---
apiVersion: v1
kind: Secret
metadata:
  name: nk-registry-key
  # namespace: staging
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJuYW5raW0uYXp1cmVjci5pbyI6IHsKCQkJImF1dGgiOiAiYm1GdWEybHRPbnB3UjBOU1YxTk9hVUYwUTFwWlowNXFjak5EVlVwWmFGUmlQVWRtTTNkViIKCQl9Cgl9Cn0
type: kubernetes.io/dockerconfigjson