name: DevOps CI-CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build_test:
    runs-on: ${{ matrix.os }}
    strategy:
     matrix: 
      os: [ubuntu-latest, windows-latest, macOs-latest]
    steps:
      - uses: actions/checkout@main
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: setup node
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}
          
  
      - name: Install dependencies
        run: |
          npm install
          npm ci

  push_to_Docker_hub:
    runs-on: ubuntu-latest
    needs: [build_test]
    
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        
      - name: Set up nankim
        uses: docker/setup-buildx-action@v1
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ../Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nknode:latest
      
      - name: Run the image in a container
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKER_HUB_USERNAME }}/nknode:latest
          run: |
            echo "runing the docker image"
            echo "Testing the nodejs app endpoints"
            echo ${{ steps.docker_build.outputs.disgest }}
          
          
        
      
  
    
        
