name: DevOps CI-CD
on:
  push:
    branches: [ main ]
jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: setup node
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}
          
      # Install application dependencies
      - name: Install dependencies
        run: |
          npm install
          npm ci
          
      # Build and test the apps
      - name: build
        run: |
          npm run build
          npm run test

  push_to_Docker_hub:
    runs-on: ubuntu-latest
    # build docker image and push to docker hub
    # The image will be build only if the app build and test successfully
    needs: [build_test]
    
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        
      - name: Set up nankim
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_TOKEN }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: .Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nknode:latest
      
      - name: Run the image in a container
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKER_HUB_USERNAME }}/nknode:latest
          run: |
            echo "runing the docker image"
            echo "Testing the nodejs app endpoints"
            echo ${{ steps.docker_build.outputs.disgest }}
          
          
        
      
  
    
        
