name: CI to Docker Hub
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.4
