name: DevOps CI-CD
on:
  push:
    branches: [ main ]
jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      
      - name: setup node
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}
          
        
      
  
    
        
