name: DevOps CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker Image
      uses: actions/docker/cli@main
      
        
